version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: repinsem/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/media
    depends_on:
      - db
  frontend:
    image: repinsem/foodgram_frontend
    env_file: .env
    command: sh -c "cp -r /app/build/static/* /frontend_static/ && cp /app/build/*.* /frontend_static/"
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: repinsem/foodgram_gateway
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_volume:/static/
      - media_volume:/media
    depends_on:
      - backend
      - frontend
